local utils = require("utils")
local apply_options = utils.apply_options
local apply_globals = utils.apply_globals

apply_globals({
	mapleader = "\\",
	loaded_gzip = true,
	loaded_tar = true,
	loaded_tarPlugin = true,
	loaded_zip = true,
	loaded_zipPlugin = true,
	loaded_getscript = true,
	loaded_getscriptPlugin = true,
	loaded_vimball = true,
	loaded_vimballPlugin = true,
	loaded_matchit = true,
	loaded_2html_plugin = true,
	loaded_logiPat = true,
	loaded_netrw = true,
	loaded_netrwPlugin = true,
	loaded_rrhelper = true,
	loaded_netrwSettings = true,
	loaded_netrwFileHandlers = true,
})

apply_options({
	compatible = false,
	mouse = "a",
	history = 10000,
	backup = false,
	writebackup = false,
	swapfile = false,
	undodir = "/tmp//,.",
	undofile = true,
	undolevels = 1000,
	undoreload = 10000,
	updatetime = 500,
	cursorline = true,
	lazyredraw = true,
	showcmd = true,
	cmdheight = 2,
	ruler = true,
	shortmess = vim.o.shortmess .. "W",
	completeopt = { "menu", "menuone", "noselect" },
	scrolloff = 4,
	sidescrolloff = 4,
	incsearch = true,
	inccommand = "nosplit",
	hlsearch = true,
	smartcase = true,
	ignorecase = true,
	gdefault = true,
	hidden = true,
	wrap = true,
	backspace = { "indent", "eol", "start" },
	display = "lastline",
	expandtab = true,
	smarttab = true,
	tabstop = 2,
	softtabstop = 2,
	shiftwidth = 2,
	autoindent = true,
	magic = true,
	number = true,
	relativenumber = true,
	pumblend = 16,
	winblend = 16,
	pumheight = 14,
	signcolumn = "yes:1",
	list = true,
	termguicolors = true,
	showbreak = "↪ ",
	listchars = {
		tab = "»·", -- has to be 2 chars or there's an error
		space = "·",
		extends = "›",
		precedes = "‹",
		nbsp = "·",
		trail = "·",
		-- eol = "↴",
	},
	fillchars = { eob = "~", fold = " " },
	timeout = true,
	timeoutlen = 1000,
	ttimeoutlen = 50,
	showtabline = 0,
	showmode = false,
	path = vim.opt.path + { "**" },
	wildmenu = true,
	wildignore = vim.opt.wildignore + {
		"*/.git/*",
		"*/.hg/*",
		"*/.svn/*.",
		"*/.vscode/*.",
		"*/.DS_Store",
		"*/dist*/*",
		"*/target/*",
		"*/builds/*",
		"*/build/*",
		"tags",
		"*/lib/*",
		"*/flow-typed/*",
		"*/node_modules/*",
		"*.png",
		"*.PNG",
		"*.jpg",
		"*.jpeg",
		"*.JPG",
		"*.JPEG",
		"*.pdf",
		"*.exe",
		"*.o",
		"*.obj",
		"*.dll",
		"*.DS_Store",
		"*.ttf",
		"*.otf",
		"*.woff",
		"*.woff2",
		"*.eot",
	},
	encoding = "utf-8",
	fileencoding = "utf-8",
	autoread = true,
	splitbelow = true,
	splitright = true,
	visualbell = true,
	errorbells = false,
	showmatch = true,
	colorcolumn = "100",
	synmaxcol = 1024,
	formatoptions = "njvcrql",
	joinspaces = false,
	foldmethod = "expr",
	foldexpr = "nvim_treesitter#foldexpr()",
	foldtext = [[substitute(getline(v:foldstart),'\\t',repeat('\ ',&tabstop),'g').'...'.trim(getline(v:foldend))]],
	foldnestmax = 3,
	foldminlines = 1,
	foldlevelstart = 99,
})

vim.cmd([[
au TextYankPost * silent! lua require("vim.highlight").on_yank({ higroup = 'IncSearch', timeout = 300 })
]])
