#!/bin/sh

# Handle external monitor
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Workspaces definition
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Basic configuration
bspc config window_gap 12
bspc config border_width 1
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus true

# Pointer configuration
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

# Make moving floating windows smooth
bspc config pointer_motion_interval 1ms

# Colors
bspc config focused_border_color "#A53841"
bspc config normal_border_color "#000000"

# Set wallpaper
feh --no-fehbg --bg-scale $DOTFILES/.wallpapers/.current

# Kill services to prevent duplicates
for srv in sxhkd polybar picom unclutter redshift; do
  while :; do
    PID=$(pidof $srv)
    if [[ -z $PID ]]; then
      break
    fi
    kill $PID
    unset PID
    sleep 0.1
  done
done

# Launch services
sxhkd &
polybar main -r &
picom -b --experimental-backends
unclutter --timeout 2 &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
