#! /bin/sh

# Workspaces definition
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Basic configuration
bspc config window_gap 12
bspc config border_width 1
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus true

# Pointer configuration
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

# Make moving floating windows smooth
# bspc config pointer_motion_interval 1ms

# Fix dumbass nvidia driver resizing OpenGL windows lag
bspc config pointer_motion_interval 50

# Kill services to prevent duplicates
for srv in sxhkd polybar picom unclutter redshift; do
  while :; do
    PID=$(pidof $srv)
    if [[ -z $PID ]]; then
      break
    fi
    kill $PID
    unset PID
    sleep 0.1
  done
done

# Launch services and programs
  # Keyboard shortcuts
  sxhkd &

  # Status bar
  polybar main -r &

  # Compositor
  picom -C -b --experimental-backends

  # Hide cursor
  unclutter --timeout 2 &

  # Night light
  redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &

  startup_lock_file=/tmp/autostart-programs.lock
  if [ ! -f $startup_lock_file ]; then
    openrgb --mode off &

    qpwgraph -a -m ~/.local/share/patchbay.qpwgraph &
    discord --start-minimized &
    steam -silent &

    touch $startup_lock_file
  fi

# Colors
bash colors &
