#! /bin/sh

# Workspaces definition
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Basic configuration
bspc config window_gap 12
bspc config border_width 1
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus true

# Pointer configuration
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

# Make moving floating windows smooth
bspc config pointer_motion_interval 1ms

# Kill services to prevent duplicates
killall sxhkd polybar picom unclutter && sleep 0.1

# Launch services
sxhkd &                             # Keyboard shortcuts
polybar main -r &                   # Status bar
picom -C -b --experimental-backends # Compositor
unclutter --timeout 2 &             # Hide cursor

startup_lock_file=/tmp/autostart-apps.lock

if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file

  openrgb --mode off

  discord --start-minimized &
fi

# Colors
bash colors &
