#! /bin/sh

bspc monitor -d web chat code music media gaming graphics term

bspc config window_gap          12
bspc config border_width         1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

################
# WINDOW RULES #
################

# Browsers
bspc rule -a Vivaldi-stable desktop=web
bspc rule -a Brave-browser desktop=web

# Chat clients
bspc rule -a discord desktop=chat

# Programming
bspc rule -a jetbrains-webstorm desktop=code
bspc rule -a jetbrains-clion desktop=code
bspc rule -a jetbrains-pycharm desktop=code

# Music players
bspc rule -a Spotify desktop=music  # Requires 'spotifywm-git' package 

# Gaming stuff
bspc rule -a Virt-manager state=floating #desktop=gaming

# Multimedia players
bspc rule -a Kodi desktop=media

# Graphics programs
bspc rule -a Blender desktop=graphics

# Other rules
bspc rule -a studentui state=floating
bspc rule -a __main__.py state=floating



#########################
# POINTER CONFIGURATION #
#########################

bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

# Make moving floating windows smooth
bspc config pointer_motion_interval 1ms


# --------------------


#######################################
# Kill services to prevent duplicates #
#######################################

killall -9 sxhkd picom dunst polybar unclutter xidlehook


###################
# Launch services #
###################

sxhkd &				# Shortcuts
picom &				# Compositor
polybar main &			# Top bar
dunst &				# Notifications
unclutter --timeout 2 &		# Hide cursor after 2 seconds

# Autolock and autosusped after certain time
xidlehook --not-when-audio --timer 300 $HOME/scripts/i3lock.sh '' &


##################
# AUTOSTART APPS #
##################


startup_lock_file=/tmp/bspwm-startup.lock

if [ ! -f $startup_lock_file ]; then
    touch $startup_lock_file

    # vivaldi-stable &
    discord &
    # spotify &
fi

bash /home/kreny/.config/bspwm/bspwm_colors.sh &
