#! /bin/sh

# Workspaces definition
bspc monitor -d web chat code audio music media gaming graphics term

# Basic configuration
bspc config window_gap		12
bspc config border_width	1
bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config ignore_ewmh_focus	true

# Pointer configuration
bspc config pointer_action1	move
bspc config pointer_action2	none
bspc config pointer_action3	resize_corner

# Make moving floating windows smooth
bspc config pointer_motion_interval 1ms


################
# WINDOW RULES #
################

# Browsers
bspc rule -a Brave-browser	desktop=web

# Chat clients
bspc rule -a discord		desktop=chat

# Programming
bspc rule -a jetbrains-clion	desktop=code
bspc rule -a jetbrains-pycharm	desktop=code
bspc rule -a jetbrains-webstorm	desktop=code

# Audio
bspc rule -a Pavucontrol	desktop=audio	state=floating
bspc rule -a QjackCtl		desktop=audio	state=floating
bspc rule -a Jack_mixer		desktop=audio	state=floating
bspc rule -a REAPER		desktop=audio	state=floating	follow=false

# Music
bspc rule -a Spotify		desktop=sound  # Requires 'spotifywm-git' package 

# Multimedia players
bspc rule -a Kodi		desktop=media
bspc rule -a Popcorn-Time	desktop=media

# Graphics programs
bspc rule -a Blender		desktop=graphics

# Other rules
bspc rule -a Virt-manager	state=floating
bspc rule -a studentui		state=floating
bspc rule -a __main__.py	state=floating

# --------------------


# Kill services to prevent duplicates
killall sxhkd polybar picom unclutter && sleep 0.1

# Launch services
sxhkd &				# Keyboard shortcuts
polybar main -r &		# Status bar
picom -C -b			# Compositor
unclutter --timeout 2 &		# Hide cursor


##################
# AUTOSTART APPS #
##################


startup_lock_file=/tmp/bspwm-autostart-apps.lock

if [ ! -f $startup_lock_file ]; then
	touch $startup_lock_file

	###############
	# AUDIO STUFF #
	###############
	sleep 5
	qjackctl &
	sleep 4
	jack_mixer -c $HOME/jack/mixer.xml &
	reaper $HOME/reaper/default.RPP &
	bspc rule -a Alacritty -o desktop=audio state=floating rectangle=802x602+1746+35 && alacritty -e bash -c "fluidsynth -a jack -m jack -r 48000 -g 1.0 ~/Orpheus_18.06.2020.sf2 && zsh" &

	########
	# APPS #
	########
	discord &
fi

# Colors
bash colors &

