theme = "kanagawa"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true

[keys.normal]
"esc" = ["keep_primary_selection", "collapse_selection"]